name: pitchupfluttersample
description: Sample on how to implement a guitar tuning app in Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  pitch_detector_dart: ^0.0.4
  pitchupdart: ^0.0.4
  flutter_audio_capture: ^1.1.6
  flutter_bloc: ^8.1.5

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true